version: "3"
services:
  xmeme_app:
    container_name: xmeme_app
    image: xmeme_app
    restart: always
    build: .
    ports:
      - "8081:8080"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
